### ISSUE TITLE
Missing prerequisites.txt file

### ISSUE THREAD

**Issue by joseagraz** [maragraziani/interpretable-WSItoRNAseq#1]
Hi
Your prerequisites.txt file is missing, could you please provide the file. 
"
To install the repo in your virtual environment, run the following:

Clone the repo
git clone https://github.com/maragraziani/interpretableWSItoRNAseq.git
Install NPM packages
python3 -m pip install -r prerequisites.txt
"

**Comment by maragraziani** [comment]
Hi!! I added it now! Thanks for spotting the missing file. 

Cheers
Mara
